#!/usr/bin/env python
#coding: utf-8

import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.use('Agg')

decisionNode = dict(boxstyle="sawtooth", fc="0.8")
leafNode = dict(boxstyle="round4", fc="0.8")
arrow_args = dict(arrowstyle="<-")

def plotNode(ax1, nodeTxt, centerPt, parentPt, nodeType):
    ax1.annotate(nodeTxt, xy=parentPt, xycoords="axes fraction", xytext=centerPt, textcoords="axes fraction",
            va="center", ha="center", bbox=nodeType, arrowprops=arrow_args)

def createPlot():
    fig = plt.figure()
    fig.clf()
    ax1 = plt.subplot(111, frameon=False)
    plotNode(ax1, U'Decision Node', (0.5, 0.1), (0.1, 0.5), decisionNode)
    plotNode(ax1, U'Leaf Node', (0.8, 0.1), (0.3, 0.5), leafNode)
    plt.show()
    fig.savefig("temp.png")

createPlot()

